EDGAPIUTL-24: ClassNotFoundException: com.bettercloud.vault.VaultException
```
java.lang.NoClassDefFoundError: com/bettercloud/vault/VaultException
	at org.folio.edge.api.utils.security.SecureStoreFactory.getSecureStore(SecureStoreFactory.java:23)
```

This is caused by the circular dependency folio-spring-system-user ↔︎ dge-api-utils.

Use `<exclusions>` in pom.xml and switch to the new Vault package name. Mention the change in the NEWS.